# Generated by Django 3.2.16 on 2023-01-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcfunding',
            name='fund',
            field=models.CharField(choices=[('SV', 'Savings'), ('SA', 'Salary')], default='SV', max_length=200),
        ),
    ]
